# type path                     mode uid    gid    age
d /run/zovive                    0750 zovive zovive -
d /run/zovive/staging            0750 zovive zovive 1h
d /dev/shm/zovive                0750 zovive zovive -
d /dev/shm/zovive/segments       0750 zovive zovive 10m
d /var/cache/zovive              0750 zovive zovive 7d
